update OpenSSL to v1.1.1i
instil/openssl-mobile pull request #1
Opened 2021-01-08 13:01 UTC by niall-robson-instil

2021-01-08 13:04 UTC, Paul-Shields commented
So the build scripts here work unmodified with this version of OpenSSL?

2021-01-21 11:18 UTC, Paul-Shields requested changes

2021-01-21 11:18 UTC, Paul-Shields commented on toolchains_path.py
> +#!/usr/bin/env python
Can we remove this file?

2021-01-21 11:18 UTC, Paul-Shields commented on build-android.sh
> +echo $toolchains_path/bin
Is this just a debug line?

```suggestion
```

2021-01-21 11:18 UTC, Paul-Shields commented on build-android.sh
> +echo $toolchains_path/bin
(These GitHub PR tools are really good!)

2021-01-21 11:18 UTC, Paul-Shields commented on build-android.sh
>  esac
I know this is just tweaking what was there before, but I'm guessing this won't work on the M1 mac. Happy to test that out, but I think with some alternate uses of `uname` we can simplify this a bit

```suggestion
toolchains_path=/toolchains/llvm/prebuilt/$(uname -s | tr A-Z a-z)-$(uname -m)
```

Or maybe 

```suggestion
OS_TYPE=$(uname -s | tr A-Z a-z)
ARCH=$(uname -m)
toolchains_path=/toolchains/llvm/prebuilt/$OS_TYPE-$ARCH
```

2021-01-21 11:20 UTC, niall-robson-instil commented on toolchains_path.py
> +#!/usr/bin/env python
yea

2021-01-21 11:26 UTC, Paul-Shields commented on build-android.sh
>  esac
Sorry, sugggestion is slightly wrong, forgot the `${ANDROID_NDK_HOME}` from the `toolchains_path`. Got too excited with the fancy tools 😄

2021-01-22 11:48 UTC, merged